package com.mtt.mapper;

import com.mtt.pojo.TbItem;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

import java.util.List;

public interface TbItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item
     *
     * @mbggenerated
     */
    @Delete({
        "delete from tb_item",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item
     *
     * @mbggenerated
     */
    @Insert({
        "insert into tb_item (id, title, ",
        "sell_point, price, ",
        "num, barcode, image, ",
        "cid, status, created, ",
        "updated)",
        "values (#{id,jdbcType=BIGINT}, #{title,jdbcType=VARCHAR}, ",
        "#{sellPoint,jdbcType=VARCHAR}, #{price,jdbcType=BIGINT}, ",
        "#{num,jdbcType=INTEGER}, #{barcode,jdbcType=VARCHAR}, #{image,jdbcType=VARCHAR}, ",
        "#{cid,jdbcType=BIGINT}, #{status,jdbcType=TINYINT}, #{created,jdbcType=TIMESTAMP}, ",
        "#{updated,jdbcType=TIMESTAMP})"
    })
    int insert(TbItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item
     *
     * @mbggenerated
     */
    int insertSelective(TbItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, title, sell_point, price, num, barcode, image, cid, status, created, updated",
        "from tb_item",
        "where id = #{id,jdbcType=BIGINT}"
    })
    @ResultMap("BaseResultMap")
    TbItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TbItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item
     *
     * @mbggenerated
     */
    @Update({
        "update tb_item",
        "set title = #{title,jdbcType=VARCHAR},",
          "sell_point = #{sellPoint,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=BIGINT},",
          "num = #{num,jdbcType=INTEGER},",
          "barcode = #{barcode,jdbcType=VARCHAR},",
          "image = #{image,jdbcType=VARCHAR},",
          "cid = #{cid,jdbcType=BIGINT},",
          "status = #{status,jdbcType=TINYINT},",
          "created = #{created,jdbcType=TIMESTAMP},",
          "updated = #{updated,jdbcType=TIMESTAMP}",
        "where id = #{id,jdbcType=BIGINT}"
    })
    int updateByPrimaryKey(TbItem record);


    List<TbItem> selectAll();
}